version: '3.9'

services:
  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - APP_ENV=docker
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
  
  db:
    container_name: db
    image: postgres:14
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=hugobler
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=kimoveis
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hugobler -d kimoveis"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
   

