version: '3.9'

services:
  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_PASSWORD=1234
      - DB=e5
      - DB_USER=kenzinho
      - SECRET_KEY=sua_chave_secreta
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
  
  db:
    container_name: db
    image: postgres:14
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=kenzinho
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=e5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kenzinho -d e5"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
   

